[package]
name = "simple_api_with_rust"
version = "0.1.0"
authors = ["millonesj<@millonesj>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iron = "0.5.*"
rand = "*"
rustc-serialize = "*"
